classify_ticket_category:
  description: >
    Analyze {subject} and {content} to classify the ticket into one of
    the predefined categories: 
    Access and Account Management
    Technical Support
    Information and Documentation
    Training and Onboarding
    Billing and Subscription
    Feature Requests and Feedback.
  expected_output: A classification label indicating the category of the ticket, based
    on its {subject} and {content}. Make sure to include only the label from the list and no other text.
  agent: ticket_classifier

assign_ticket_priority:
  description: >
    Evaluate customer urgency and sentiment from {subject} and {content} 
    and ticket category classification to assign a priority level. 
    Information and Documentation tickets should be assigned a Low priority.
    Feature Requests and Feedback tickets should be assigned a Low priority unless there is a need for urgency expressed by the customer.
    Billing and Subscription tickets should always be assigned a High priority.

    Use one of the following priority levels:
    High
    Medium
    Low
  expected_output: >
    A priority level for the ticket, determined by analyzing the urgency
    and sentiment of its {subject} and {content}. Make sure to include only the label from the list and no other text.
  context:
    - classify_ticket_category
  agent: priority_assigner

generate_draft_response:
  description: >
    Use the available tools to search crewai.com, docs.crewai.com, and
    help.crewai.com for relevant information to create a draft response to the ticket:
    Subject: {subject}
    Content: {content}
    in the context of the CrewAI Enterprise Platform. Use the CSV
    RAG Search Tool to search a CSV file for relevant information to create a draft
    response. Use the JSON RAG Search Tool to search a JSON file for relevant information
    to create a draft response.

    If the Subject is "Bot-Created Ticket" ignore the subject and only use the content.
    If available, provide a link to the source of the information in the draft response.
    Ensure you do not recommend contacting support.
  expected_output: >
    A draft response for the ticket.
  agent: response_generator

prepare_response:
  description: >
    Prepare a response for a customer support ticket.
  expected_output: >
    # Ticket ID: *{ticket_id}*

    * URL: https://app.hubspot.com/contacts/45732688/ticket/{ticket_id}
    * Subject: *{subject}*
    * Classification: *[classification category]*
    * Priority: *[priority level]*

    ## Suggested response:

    [draft response]
  agent: support_manager
  context:
    - classify_ticket_category
    - assign_ticket_priority
    - generate_draft_response